image:
  - Visual Studio 2015
  - Ubuntu
  - macOS

platform:
  - x64

environment:
  nodejs_version: "12"

install:
  - cmd: powershell Install-Product node $env:nodejs_version $env:platform
  - sh: nvm install $nodejs_version
  - git submodule update --init --recursive
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - npm run prebuild

artifacts:
  - path: prebuilds
    name: $(APPVEYOR_BUILD_WORKER_IMAGE)
